const PREFIX = "companies";

const actionTypes = {
  FETCH_REQUEST: `${PREFIX}/FETCH_REQUEST`,
  FETCH_SUCCESS: `${PREFIX}/FETCH_SUCCESS`,
  FETCH_FAILURE: `${PREFIX}/FETCH_FAILURE`,
  ADD_ITEM_REQUEST: `${PREFIX}/ADD_ITEM_REQUEST`,
  ADD_ITEM_SUCCESS: `${PREFIX}/ADD_ITEM_SUCCESS`,
  ADD_ITEM_FAILURE: `${PREFIX}/ADD_ITEM_FAILURE`,
  FILTER: `${PREFIX}/FILTER`,
  DELETE_ITEM: `${PREFIX}/DELETE_ITEM`
};

export { actionTypes };
